import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className='mt-20 flex justify-center items-center'>
        <h1 className='text-2xl font-bold'>Click on menu</h1>
      </div>


    </div>
  )
}
